fix(make): ensures tools are always in the correct version
Previously, once a tool (like `kustomize` or `controller-gen`) was downloaded,
even if the version defined in `Makefile` changed, the old tool would be used if present
in `LOCALBIN`.

If the outdated tool modifies code incorrectly, this could lead to unnecessary noise
(and even bugs or errors) in PRs.

### Steps to reproduce

1. `rm -rf ./bin`
1. `git checkout 5db4925` (that's from when my `LOCALBIN` was ;))
1. `make`
1. `git checkout -`
1. `make`

<details>
<summary>Errors when having outdated tooling</summary>

```sh
✦ ❯ make
# Any customization needed, apply to a patch in the kustomize.yaml file on webhooks
/home/bartek/code/rhods/model-serving/odh-model-controller/bin/controller-gen rbac:roleName=odh-model-controller-role,headerFile="hack/manifests_boilerplate.yaml.txt" crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/home/bartek/.gvm/pkgsets/go1.22/global/pkg/mod/k8s.io/api@v0.31.1/core/v1/doc.go:21:1: missing argument "" (at <input>)
/home/bartek/.gvm/pkgsets/go1.22/global/pkg/mod/k8s.io/api@v0.31.1/core/v1/doc.go:21:1: missing argument "" (at <input>)
k8s.io/api/core/v1:-: unknown type "k8s.io/api/core/v1".ObjectReference
k8s.io/api/core/v1:-: unknown type "k8s.io/api/core/v1".ObjectReference
k8s.io/api/core/v1:-: unknown type "k8s.io/api/core/v1".ObjectReference
k8s.io/api/core/v1:-: unknown type "k8s.io/api/core/v1".ObjectReference
k8s.io/api/core/v1:-: unknown type "k8s.io/api/core/v1".ObjectReference
k8s.io/api/core/v1:-: unknown type "k8s.io/api/core/v1".ObjectReference
k8s.io/api/core/v1:-: unknown type "k8s.io/api/core/v1".ObjectReference
k8s.io/api/core/v1:-: unknown type "k8s.io/api/core/v1".ObjectReference
k8s.io/api/core/v1:-: unknown type "k8s.io/api/core/v1".ObjectReference
k8s.io/api/core/v1:-: unknown type "k8s.io/api/core/v1".ObjectReference
github.com/opendatahub-io/odh-model-controller/api/nim/v1:-: unable to locate schema for type "k8s.io/api/core/v1".ObjectReference
github.com/opendatahub-io/odh-model-controller/api/nim/v1:-: unable to locate schema for type "k8s.io/api/core/v1".ObjectReference
github.com/opendatahub-io/odh-model-controller/api/nim/v1:-: unable to locate schema for type "k8s.io/api/core/v1".ObjectReference
github.com/opendatahub-io/odh-model-controller/api/nim/v1:-: unable to locate schema for type "k8s.io/api/core/v1".ObjectReference
github.com/opendatahub-io/odh-model-controller/api/nim/v1:-: unable to locate schema for type "k8s.io/api/core/v1".ObjectReference
Error: not all generators ran successfully
run `controller-gen rbac:roleName=odh-model-controller-role,headerFile=hack/manifests_boilerplate.yaml.txt crd webhook paths=./... output:crd:artifacts:config=config/crd/bases -w` to see all available markers, or `controller-gen rbac:roleName=odh-model-controller-role,headerFile=hack/manifests_boilerplate.yaml.txt crd webhook paths=./... output:crd:artifacts:config=config/crd/bases -h` for usage
make: *** [Makefile:50: manifests] Error 1
```

</details>

With this PR, we always remove the symlink first to recreate it at the end.
Therefore, it is always pointing to the desired version, regardless of whether
the actual `go install` needs to be invoked.

Signed-off-by: Bartosz Majsak <bartosz.majsak@gmail.com>